/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2012 Google Inc.
 */

//
//  GTLTictactoeScore.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   tictactoe/v1
// Classes:
//   GTLTictactoeScore (0 custom class methods, 4 custom properties)

#import "GTLTictactoeScore.h"

#import "GTLTictactoeUser.h"

// ----------------------------------------------------------------------------
//
//   GTLTictactoeScore
//

@implementation GTLTictactoeScore
@dynamic identifier, outcome, played, player;

+ (NSDictionary *)propertyToJSONKeyMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObject:@"id"
                                forKey:@"identifier"];
  return map;
}

@end
