/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2012 Google Inc.
 */

//
//  GTLTictactoeBoard.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   tictactoe/v1
// Classes:
//   GTLTictactoeBoard (0 custom class methods, 1 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

// ----------------------------------------------------------------------------
//
//   GTLTictactoeBoard
//

@interface GTLTictactoeBoard : GTLObject
@property (copy) NSString *state;
@end
