/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2012 Google Inc.
 */

//
//  GTLTictactoeBoard.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   tictactoe/v1
// Classes:
//   GTLTictactoeBoard (0 custom class methods, 1 custom properties)

#import "GTLTictactoeBoard.h"

// ----------------------------------------------------------------------------
//
//   GTLTictactoeBoard
//

@implementation GTLTictactoeBoard
@dynamic state;
@end
