/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2012 Google Inc.
 */

//
//  GTLTictactoe.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   tictactoe/v1

#import "GTLTictactoeBoard.h"
#import "GTLTictactoeScore.h"
#import "GTLTictactoeScores.h"
#import "GTLTictactoeUser.h"

#import "GTLQueryTictactoe.h"
#import "GTLServiceTictactoe.h"
