/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2012 Google Inc.
 */

//
//  GTLTictactoeScores.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   tictactoe/v1
// Classes:
//   GTLTictactoeScores (0 custom class methods, 1 custom properties)

#import "GTLTictactoeScores.h"

#import "GTLTictactoeScore.h"

// ----------------------------------------------------------------------------
//
//   GTLTictactoeScores
//

@implementation GTLTictactoeScores
@dynamic items;

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObject:[GTLTictactoeScore class]
                                forKey:@"items"];
  return map;
}

@end
