/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2012 Google Inc.
 */

//
//  GTLTictactoeUser.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   tictactoe/v1
// Classes:
//   GTLTictactoeUser (0 custom class methods, 5 custom properties)

#import "GTLTictactoeUser.h"

// ----------------------------------------------------------------------------
//
//   GTLTictactoeUser
//

@implementation GTLTictactoeUser
@dynamic authDomain, email, federatedIdentity, nickname, userId;
@end
